### ISSUE TITLE
Doesn't work subscriber on mono

### ISSUE THREAD

**Issue by Prstork** [zoetrope/RosSharp#3]
Hello,
I'm trying to use RosSharp (Ubuntu14.04/RosIndigo/MonoDevelop) but I can't get the Listener sample to work.
The subscriber and the listener seem to be connected but nothing is received, I can't see anything in the console of MonoDevelop.
Can you help me please ? 
![listener_rossharp](https://cloud.githubusercontent.com/assets/17593092/15705474/71b3cb22-27e7-11e6-8d5d-6bdccb64c884.png)
![rosnode_list](https://cloud.githubusercontent.com/assets/17593092/15705471/71ae1330-27e7-11e6-9797-665bffc29fb4.png)
![rostopic_info](https://cloud.githubusercontent.com/assets/17593092/15705473/71af4c3c-27e7-11e6-9a54-bfc8ea600d07.png)
![talkertest](https://cloud.githubusercontent.com/assets/17593092/15705472/71aef2d2-27e7-11e6-84c3-4fd19cfc475e.png)

**Comment by zoetrope** [comment]
I'll check it.
Please wait a few days.

**Comment by Prstork** [comment]
No problem, thanks for your help !
About the previous post, I took the rosnode list screenshot at the wrong time, there is another node called /TalkerTest .

**Comment by zoetrope** [comment]
I investigated this problem, and found the cause.
RosSharp uses `Socket.BeginConnect` method with `DnsEndPoint`.
But mono does not implement this method. 
I got following error on simple code.

```
System.NotImplementedException: The method or operation is not implemented.
  at System.Net.EndPoint.Serialize () <0x41c7c010 + 0x00013> in <filename unknown>:0 
  at System.Net.Sockets.Socket.BeginConnect (System.Net.EndPoint end_point, System.AsyncCallback callback, System.Object state) <0x41c7b5f0 + 0x00297> in <filename unknown>:0 
```

If you can build RosSharp, could you try to change like following code?
(This code accept only IP Address for `ROS_HOSTNAME`)

``` diff
--- a/RosSharp/Transport/TcpRosClient.cs
+++ b/RosSharp/Transport/TcpRosClient.cs
@@ -81,8 +81,7 @@ namespace RosSharp.Transport

         public Task ConnectAsync(string hostName, int portNumber)
         {
-            var hostEntry = new DnsEndPoint(hostName, portNumber);
+            var hostEntry = new IPEndPoint(IPAddress.Parse(hostName), portNumber);
             _socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

             return _socket.ConnectTaskAsync(hostEntry);
```

**Comment by Prstork** [comment]
Hello, thank you for your answer !

> This code accept only IP Address for ROS_HOSTNAME

So should I change anything else in the main code ?

**Comment by zoetrope** [comment]
You can set ROS_HOSTNAME by code or app.config or environment variable.
example: write following in main code before Ros.InitNodeAsyc.

```
Ros.HostName = "192.168.1.11";
```

**Comment by Prstork** [comment]
Ok, I will try !
But I worked around the problem using service and client !
